Fix Operation name logging for Netty based applications
open-telemetry/opentelemetry-java-instrumentation pull request #2317
Opened 2021-02-17 15:45 UTC by neinoi

Fix Operation name logging for Netty based applications

(@trask Report of PR #1494 on ApplicationInsights-Java repo)

2021-02-17 17:58 UTC, laurit commented
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
> Instrumentation MUST NOT default to using URI path as span name

2021-02-17 19:15 UTC, neinoi commented
@laurit if I follow your recommandation, all my operations will be « HTTP GET » … so I can let « netty.request » the result is the same.

These are more usefull : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span

2021-02-17 19:57 UTC, iNikem requested changes
As @laurit correctly noticed, using full URL (even without query string) violates Otel semantic convention and general requirement for low cardinality of the span names.

2021-02-17 20:22 UTC, neinoi commented
Here without my modifications : 

![image](https://user-images.githubusercontent.com/8634059/108262955-990d7980-7133-11eb-8a29-aa319819dc71.png)
I agree, for low cardinality it’s perfect, all calls have the same name.

Here after my modifications (first version, before my last modifications) : 
![image](https://user-images.githubusercontent.com/8634059/108263086-c78b5480-7133-11eb-8248-db75eae98350.png)
It’s not perfect, but I think a bit better.

2021-02-18 05:54 UTC, trask commented
Hi @neinoi! As appealing as it is to use the path as the span name, it doesn't work well for applications that have an unbounded number of (parameterized) paths.

Since the one-size-fits-all span name is not that great (and we all agree that `HTTP GET` is not that great 😄), there are ways for applications to customize the span name.

Since you are using Application Insights, if you open an issue in that repo, I can explain the different options for customizing the span name (which are a bit specific to Application Insights, since we don't use the OTel Collector, and our OTel API interoperability is under a preview flag).

If you'd like to continue with this PR, changing the span name to `HTTP {method}` would be great, we missed `netty.request` previously when updating to the OpenTelemetry semantic conventions, and it would be a good update this.

2021-02-18 13:54 UTC, neinoi commented
Hi @trask ,
I’ve modified the code to have `HTTP {method}` for the span name.
For the options, is this the good place to go : [java-standalone-telemetry-processors](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors) ?
(I will transmit these informations to my successor in my current project)

2021-02-18 23:41 UTC, trask reviewed
Thanks @neinoi!

> For the options, is this the good place to go : [java-standalone-telemetry-processors](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors) ?

Yes, that's a good option. Another option is https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#override-the-request-telemetry-name-using-the-2x-sdk.

2021-02-18 23:42 UTC, trask approved these changes

2021-02-19 09:03 UTC, anuraaga approved these changes

2021-02-19 10:11 UTC, iNikem approved these changes

2021-02-19 17:59 UTC, merged