Document captured HTTP headers configuration options
open-telemetry/opentelemetry-java-instrumentation pull request #4321
Opened 2021-10-07 13:40 UTC by mateuszrzeszutek

I moved docs for properties that are common to all instrumentations to a separate file - and created a new directory for instrumentation configuration docs. Perhaps in the future we'll have a `config/reactor-netty.md` file with Reactor Netty speficic configs, a `config/spring-batch.md` with Spring Batch configs and so on.

CC @theletterf

2021-10-07 14:01 UTC, theletterf requested changes

2021-10-07 14:01 UTC, theletterf commented on docs/config/common.md
> +. The following properties may be used to define which headers should be captured:
```suggestion
. Use the following properties to define which HTTP headers you want to capture:
```

2021-10-07 14:01 UTC, theletterf commented on docs/config/common.md
> +These configuration options are supported by all javaagent HTTP client and server instrumentations.
```suggestion
These configuration options are supported by all HTTP client and server instrumentations.
```

2021-10-07 14:01 UTC, theletterf commented on docs/config/common.md
> +NOTE: the property/env variable names listed in the table above are still experimental, and thus are
```suggestion
> **Note**: The property/environment variable names listed in the table are still experimental, and thus are
```

2021-10-07 14:01 UTC, theletterf commented on docs/config/common.md
> +subject to change!
```suggestion
subject to change.
```

2021-10-07 17:28 UTC, trask commented on docs/config/common.md
> +. Use the following properties to define which HTTP headers you want to capture:
```suggestion
[semantic convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-request-and-response-headers).
Use the following properties to define which HTTP headers you want to capture:
```

2021-10-08 04:51 UTC, theletterf commented on docs/config/common.md
> +| `otel.instrumentation.common.experimental.capture-http-headers.server.response` | `OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CAPTURE_HTTP_HEADERS_SERVER_RESPONSE` | A comma-separated list of HTTP he
Wait, they’re still open for discussion? I love naming vars. Let’s discuss today. :)

2021-10-08 17:53 UTC, merged